In [1]:
"""
numpy常用于数组的快速操作
包括数学、逻辑、形状操作、排序、选择、输入输出、离散傅立叶变换、基本线性代数，基本统计运算和随机模拟
ndarray 对象封装了python原生的同数据类型的 n 维数组
NumPy 数组在创建时具有固定的大小，与Python的原生数组对象（可以动态增长）不同
更改ndarray的大小将创建一个新数组并删除原来的数组
功能基础：矢量化+广播
"""

'\nnumpy常用于数组的快速操作\n包括数学、逻辑、形状操作、排序、选择、输入输出、离散傅立叶变换、基本线性代数，基本统计运算和随机模拟\nndarray 对象封装了python原生的同数据类型的 n 维数组\nNumPy 数组在创建时具有固定的大小，与Python的原生数组对象（可以动态增长）不同\n更改ndarray的大小将创建一个新数组并删除原来的数组\n功能基础：矢量化+广播\n'

In [2]:
"""
NumPy的主要对象是同构多维数组。它是一个元素表（通常是数字），所有类型都相同，由非负整数元组索引。在NumPy维度中称为 轴 。
"""
import numpy as np
a=np.arange(15).reshape(3,5)
print(a)
print(a.ndim)#2 数组的轴（维度）的个数
print(a.shape)#(3, 5)#数组形状
print(a.dtype)#int64 数组中元素类型的对象
print(a.itemsize)#8 数组中每个元素的字节大小 int64/8=8
print(a.size)#15 数组元素的总数

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
2
(3, 5)
int64
8
15


In [3]:
"""
数组的创建
数组的元素最初是未知的，但它的大小是已知的
"""
b = np.zeros(6)#[0. 0. 0. 0. 0. 0.]
print(b)
c = np.ones(6)#[1. 1. 1. 1. 1. 1.]
print(c)
d = np.arange(10,30,5)#[10 15 20 25] 包头去尾
print(d)
e = np.empty(6)#[1. 1. 1. 1. 1. 1.]
print(e)
f = np.ones_like(b)#[1. 1. 1. 1. 1. 1.]
print(f)
g = np.zeros_like(c)#[0. 0. 0. 0. 0. 0.]
print(g)
h = np.linspace(0.1,2.2,5)#[0.1   0.625 1.15  1.675 2.2  ] linspace函数来接收我们想要的元素数量的函数,而不是步长（step）包头包尾
print(h)

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[10 15 20 25]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0.]
[0.1   0.625 1.15  1.675 2.2  ]


In [4]:
"""
打印数组
最后一个轴从左到右打印，
倒数第二个从上到下打印，
其余部分也从上到下打印，每个切片用空行分隔。
然后将一维数组打印为行，将二维数据打印为矩阵，将三维数据打印为矩数组表。
如果数组太大而无法打印，NumPy会自动跳过数组的中心部分并仅打印角点
要禁用此行为并强制NumPy打印整个数组  np.set_printoptions(threshold=sys.maxsize) 
"""
a = np.arange(6)
print(a)#[0 1 2 3 4 5]
b = np.arange(12).reshape(3,4)
print(b)
c = np.arange(24).reshape(2,3,4)
print(c)

[0 1 2 3 4 5]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [5]:
"""
数组上的算术运算符会应用到 元素 级别
"""
A = np.array([[1,2],[2,3]])
B = np.array([[2,1],[2,4]])
print(A*B)#按元素进行运算
print(A.dot(B))#矩阵乘积
print(A@B)#矩阵乘积
x = np.random.randn(3,4)
print(x)
print(x.sum())
print(x.min())
print(x.max())
print(x.min(axis=0))#求解每一列的最小值
print(x.min(axis=1))#求解每一行的最小值
print(x.sum(axis=0))#对每一列求和
print(x.cumsum(axis=1))# cumulative sum along each row 累加求和

[[ 2  2]
 [ 4 12]]
[[ 6  9]
 [10 14]]
[[ 6  9]
 [10 14]]
[[ 0.70916646  0.36801581  1.00117587 -1.01121524]
 [-0.19380714 -0.36687885 -0.68471225  0.08970086]
 [ 1.06266234  1.16091439  1.61111391  0.7687633 ]]
4.5148994621259515
-1.0112152381830368
1.6111139101133558
[-0.19380714 -0.36687885 -0.68471225 -1.01121524]
[-1.01121524 -0.68471225  0.7687633 ]
[ 1.57802166  1.16205135  1.92757753 -0.15275108]
[[ 0.70916646  1.07718227  2.07835814  1.0671429 ]
 [-0.19380714 -0.56068598 -1.24539823 -1.15569738]
 [ 1.06266234  2.22357673  3.83469064  4.60345394]]


In [6]:
"""
通函数 提供常见的数学函数
这些函数在数组上按元素进行运算，产生一个数组作为输出
"""
A = np.array([1,2,3])
print(A)
B = np.exp(A)
print(B)
C = np.sqrt(A)
print(C)
D = np.add(B,C)
print(D)

[1 2 3]
[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[ 3.71828183  8.80326966 21.81758773]


In [7]:
"""
索引、切片和迭代
"""
a = np.arange(6)
print(a)
b = np.arange(6)*3
print(b)#每个元素乘以三
c = np.arange(6)**3
print(c)#每个元素三次幂
print(a[2])
print(a[2:5])#包头去尾
print(a[1:])#包头
print(a[:5])#去尾
print(a[-1])#末尾元素
a[0:6:2]=-100
#从0开始，0，2，4索引位置元素改成-100
print(a)
a[ : :-1]
print(a[ : :-1])#逆序排列
print(a)#需要注意的是，这里重新安排了一个新的数组，不是在原数组上进行操作！！！！！！
b = np.array([[1,2,3,4,5],[3,4,5,6,7],[5,6,7,8,9],[6,7,8,9,10],[7,8,9,10,11]])
print(b)
#print(b[2])#无法索引
print(b[-1])#当提供的索引少于轴的数量时，缺失的索引被认为是完整的切片
print(b[1,1])
"""
多维的数组每个轴可以有一个索引。这些索引以逗号分隔的元组给出
b[i] 方括号中的表达式 i 被视为后面紧跟着 : 的多个实例，用于表示剩余轴
"""
#相当于第一个逗号前面的是行，第二个逗号后面的是列
print(b[0:5,1])#第二列的所有元素
print(b[:,1])
print(b[0:5,2])#第三列的所有元素
print(b[0:3,:])#前三行的所有元素
print(b[0:3,0:3])#前三行前三列的所有元素

#对多维数组进行 迭代（Iterating） 是相对于第一个轴完成的
for row in b:
    print(row)
#如果想要对数组中的每个元素执行操作，可以使用flat属性
for element in b.flat:
    print(element)

[0 1 2 3 4 5]
[ 0  3  6  9 12 15]
[  0   1   8  27  64 125]
2
[2 3 4]
[1 2 3 4 5]
[0 1 2 3 4]
5
[-100    1 -100    3 -100    5]
[   5 -100    3 -100    1 -100]
[-100    1 -100    3 -100    5]
[[ 1  2  3  4  5]
 [ 3  4  5  6  7]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]
 [ 7  8  9 10 11]]
[ 7  8  9 10 11]
4
[2 4 6 7 8]
[2 4 6 7 8]
[3 5 7 8 9]
[[1 2 3 4 5]
 [3 4 5 6 7]
 [5 6 7 8 9]]
[[1 2 3]
 [3 4 5]
 [5 6 7]]
[1 2 3 4 5]
[3 4 5 6 7]
[5 6 7 8 9]
[ 6  7  8  9 10]
[ 7  8  9 10 11]
1
2
3
4
5
3
4
5
6
7
5
6
7
8
9
6
7
8
9
10
7
8
9
10
11


In [8]:
"""
形状操作
"""
a = np.floor(10*np.random.random((3,4)))
b = np.array(10*np.random.random((3,4)))
c = np.floor(b)#向下取整
d = np.ceil(b)#向上取整
print(a)
print(b)
print(c)
print(d)
"""
################3以下三个命令都返回一个修改后的数组，但不会更改原始数组################
"""
print(a.ravel())#返回一个数据流 flattened
print(a)
print(a.reshape(2,6))#返回一个新的数组形状
print(a)
print(a.T)#返回数组的转置
print(a)
#reshape函数返回带有修改形状的参数，而ndarray.resize方法会修改数组本身
print(a.resize(2,6))#None
print(a)
#如果在 reshape 操作中将 size 指定为-1，则会自动计算其他的 size 大小
print(a.reshape(3,-1))

[[5. 4. 4. 1.]
 [0. 0. 7. 4.]
 [4. 3. 4. 7.]]
[[2.45687732 3.44447621 7.9767068  8.43686832]
 [3.66740908 3.84174402 0.38073085 6.97697918]
 [2.86185847 5.26209818 4.89178952 6.51116366]]
[[2. 3. 7. 8.]
 [3. 3. 0. 6.]
 [2. 5. 4. 6.]]
[[3. 4. 8. 9.]
 [4. 4. 1. 7.]
 [3. 6. 5. 7.]]
[5. 4. 4. 1. 0. 0. 7. 4. 4. 3. 4. 7.]
[[5. 4. 4. 1.]
 [0. 0. 7. 4.]
 [4. 3. 4. 7.]]
[[5. 4. 4. 1. 0. 0.]
 [7. 4. 4. 3. 4. 7.]]
[[5. 4. 4. 1.]
 [0. 0. 7. 4.]
 [4. 3. 4. 7.]]
[[5. 0. 4.]
 [4. 0. 3.]
 [4. 7. 4.]
 [1. 4. 7.]]
[[5. 4. 4. 1.]
 [0. 0. 7. 4.]
 [4. 3. 4. 7.]]
None
[[5. 4. 4. 1. 0. 0.]
 [7. 4. 4. 3. 4. 7.]]
[[5. 4. 4. 1.]
 [0. 0. 7. 4.]
 [4. 3. 4. 7.]]


In [9]:
"""
将不同数组堆叠在一起
"""
a = np.floor(10*np.random.random((2,2)))
print(a)
b = np.floor(10*np.random.random((2,2)))
print(b)
print(np.vstack((a,b)))#往下堆叠Stack arrays in sequence vertically (row wise).
print(np.hstack((a,b)))#往右堆叠Stack arrays in sequence horizontally (column wise).
#通过沿一个轴堆叠数字来创建数组
c = np.r_[np.array([1,2,3]),0,np.array([4,5,6])]#Translates slice objects to concatenation along the first axis.
print(c)
"""
c_:
arrays will be stacked along their last axis after being upgraded to at least 2-D with 1’s post-pended 
to the shape (column vectors made out of 1-D arrays).
"""
d = np.c_[np.array([1,2,3]), np.array([4,5,6])]#Translates slice objects to concatenation along the second axis
print(d)

[[5. 4.]
 [9. 5.]]
[[2. 0.]
 [1. 3.]]
[[5. 4.]
 [9. 5.]
 [2. 0.]
 [1. 3.]]
[[5. 4. 2. 0.]
 [9. 5. 1. 3.]]
[1 2 3 0 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [10]:
"""
数组拆分
np.hsplit可以沿数组的水平轴拆分数组，方法是指定要返回的形状相等的数组的数量，或者指定应该在其之后进行分割的列
np.vsplit沿垂直轴分割
"""
a = np.floor(10*np.random.random((2,12)))
print(a)
b = np.hsplit(a,3)
print(b)
print(b[2])
c = np.hsplit(a,(3,4))#指定分割 第三列 第四列
print(c)
e = np.vsplit(a,2)
print(e)

[[0. 6. 5. 7. 0. 9. 3. 9. 2. 2. 6. 5.]
 [7. 1. 4. 8. 6. 1. 5. 9. 0. 3. 1. 5.]]
[array([[0., 6., 5., 7.],
       [7., 1., 4., 8.]]), array([[0., 9., 3., 9.],
       [6., 1., 5., 9.]]), array([[2., 2., 6., 5.],
       [0., 3., 1., 5.]])]
[[2. 2. 6. 5.]
 [0. 3. 1. 5.]]
[array([[0., 6., 5.],
       [7., 1., 4.]]), array([[7.],
       [8.]]), array([[0., 9., 3., 9., 2., 2., 6., 5.],
       [6., 1., 5., 9., 0., 3., 1., 5.]])]
[array([[0., 6., 5., 7., 0., 9., 3., 9., 2., 2., 6., 5.]]), array([[7., 1., 4., 8., 6., 1., 5., 9., 0., 3., 1., 5.]])]


In [11]:
"""
拷贝和视图
"""
#完全不复制
#简单分配不会复制数组对象或其数据。
a = np.arange(12)
b = a 
###############a and b are two names for the same ndarray object#####################
print(a)
print(b)
b.shape=(3,4)
print(a)
print(b)
print(id(a),id(b))#a与b的id完全相同


#视图/浅拷贝 不同的数组对象可以共享相同的数据。view方法创建一个查看相同数据的新数组对象
c = a.view()
print(c is a)#False
print(c.base is a)#True ######   c is a view of the data owned by a
print(id(c),id(a))
c.shape=(6,2)
print(a.shape)#a数组的形状不变
c[0,0]=1000
print(a)#a数组的数据改变

#切片数组会返回一个视图
s = a[:,0:1]
print(s)
s[:]=10
print(a)



#深拷贝 copy方法生成数组及其数据的完整副本。
d = a.copy()
#d doesn't share anything with a
print(d)
print(id(a),id(d))
print(d is a)
print(d.base is a)
"""
假设a是一个巨大的中间结果，最终结果b只包含a的一小部分，那么在用切片构造b时应该做一个深拷贝
"""
a = np.arange(int(1e8))
b = a[:100].copy()
del a

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
4369994176 4369994176
False
True
4369994496 4369994176
(3, 4)
[[1000    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]
[[1000]
 [   4]
 [   8]]
[[10  1  2  3]
 [10  5  6  7]
 [10  9 10 11]]
[[10  1  2  3]
 [10  5  6  7]
 [10  9 10 11]]
4369994176 4369994816
False
False


In [12]:
"""
索引技巧
"""
a = np.arange(12)**2
print(a)
i = np.array([1,1,3,8,5])
print(a[i])
j = np.array([[1,2],[3,4]])
print(a[j])
#当索引数组a是多维的时，单个索引数组指的是第一个维度a 
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
i = np.array([1,1,2])#按行索引
print(a[i])
j = np.array([[1,2],[0,1]])
print(a[j])
#可以同时为多个维度提供索引。每个维度的索引数组必须具有相同的形状。
a = np.arange(12).reshape(3,4)
print(a)
i = np.array([[1,2],[0,1]])
print(a[i])
j = np.array([[0,1],[1,2]])
print(a[j])
print(a[i,j])

#使用数组索引的另一个常见用法是搜索与时间相关系列的最大值
time = np.linspace(20, 145, 5)
print(time)
data = np.sin(np.arange(20)).reshape(5,4)
print(data)
ind = data.argmax(axis=0)#每一列的最大值索引
print(ind)
ind2 = data.argmax(axis=1)#每一行的最大值索引
print(ind2)
time_max = time[ind]
print(time_max)

#使用数组索引作为分配给的目标
a = np.arange(5)
print(a)
a[[1,2,3,4]]=1000
print(a)
#当索引列表包含重复时，分配会多次完成，留下最后一个值
a[[0,0,2]]=[1,2,3]#索引列表为[0,0,2]
print(a)

"""
使用布尔数组进行索引
明确地选择我们想要的数组中的哪些项目以及我们不需要的项目
"""
a = np.arange(12).reshape(3,4)
b = a > 4
print(a)
print(b)#数组元素均为布尔值
print(a[b])#索引布尔值为True的元素值
a[b] = 0#数组a中大于4的元素全部置零

#布尔索引切片
a = np.arange(12).reshape(3,4)
b1 = np.array([False,True,False])
b2 = np.array([True,True,False,False])
print(a)
print(a[b1])
print(a[b1,:])
print(a[:,b2])
print(a[b1,b2])

[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 1  1  9 64 25]
[[ 1  4]
 [ 9 16]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [4 5 6]
 [7 8 9]]
[[[4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 4  5  6  7]
  [ 8  9 10 11]]]
[[4 9]
 [1 6]]
[ 20.    51.25  82.5  113.75 145.  ]
[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[2 3 0 2 3]
[ 82.5   20.   113.75  51.25]
[0 1 2 3 4]
[   0 1000 1000 1000 1000]
[   2 1000    3 1000 1000]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[4 5 6 7

In [13]:
"""
ix_函数
可用于组合不同的向量
"""
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([10,100,1000,1000,10])
ax,bx,cx = np.ix_(a,b,c)
print(ax)
print(bx)
print(cx)
print(ax.shape,bx.shape,cx.shape) #(3, 1, 1) (1, 4, 1) (1, 1, 5)
result = ax+bx*cx
print(result)
print(result.shape)#(3, 4, 5)
print(result[2,3,4]==a[2]+b[3]*c[4])#True

[[[1]]

 [[2]]

 [[3]]]
[[[4]
  [5]
  [6]
  [7]]]
[[[  10  100 1000 1000   10]]]
(3, 1, 1) (1, 4, 1) (1, 1, 5)
[[[  41  401 4001 4001   41]
  [  51  501 5001 5001   51]
  [  61  601 6001 6001   61]
  [  71  701 7001 7001   71]]

 [[  42  402 4002 4002   42]
  [  52  502 5002 5002   52]
  [  62  602 6002 6002   62]
  [  72  702 7002 7002   72]]

 [[  43  403 4003 4003   43]
  [  53  503 5003 5003   53]
  [  63  603 6003 6003   63]
  [  73  703 7003 7003   73]]]
(3, 4, 5)
True


In [14]:
"""
线性代数
参阅numpy文件夹中的linalg.py.
help(np.linalg)
"""
a = np.array([[1.0,2.0],[3.0,4.0]])
print(a)
b = a.transpose()
print(b)
"""
help(np.linalg.inv)
Compute the (multiplicative) inverse of a matrix.
Given a square matrix `a`, return the matrix `ainv` satisfying
    ``dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])``.
"""
c = np.linalg.inv(a)
d = np.linalg.inv(b)
print(c)
print(d)
"""
solve(a, b)
    Solve a linear matrix equation, or system of linear scalar equations.
    
    Computes the "exact" solution, `x`, of the well-determined, i.e., full
    rank, linear matrix equation `ax = b`.
"""
y = np.array([[5.], [7.]])
x = np.linalg.solve(a,y)
print(x)
z = np.linalg.eig(a)#Compute the eigenvalues and right eigenvectors of a square array.
print(a)

[[1. 2.]
 [3. 4.]]
[[1. 3.]
 [2. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   1.5]
 [ 1.  -0.5]]
[[-3.]
 [ 4.]]
[[1. 2.]
 [3. 4.]]


In [15]:
"""
自动整形机制
"""
a = np.arange(30)
a.shape = 2,-1,3   # -1 means "whatever is needed"
print(a.shape)

(2, 5, 3)


In [16]:
"""
数据类型的一些转换
"""
a = np.array([1,2,3])
print(a.dtype)#int64
b = np.int_(a)
print(b.dtype)#int64
c = np.float_(a)
print(c.dtype)#float64
d = np.array([1,2,3],dtype=float)
print(d.dtype)#float64
e = np.array([1,2,3],dtype=np.float32)
print(e.dtype)#float32
f = a.astype(np.float32)#不改变原来数组的类型
print(a.dtype,f.dtype)#int64 float32
print(id(a),id(f))#id 不同
print(f.base is a)#False

int64
int64
float64
float64
float32
int64 float32
4579313264 4369994976
False


In [17]:
"""
结构化数组 类似C的结构体
"""
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
print(x)
print(x[0])

[('Rex', 9, 81.) ('Fido', 3, 27.)]
('Rex', 9, 81.)


In [18]:
"""
数组的一些初始化操作
"""
x = np.array([[]*10])
print(x.shape)
y = np.array([]*10)
print(y.shape)
z = np.array([0]*10)
print(z.shape)
a = np.array([]*i for i in range(10))
print(a.shape)
b = np.array([[]*i for i in range(10)])
print(b.shape)#(10,0)
c = np.array([0*i for i in range(10)])
print(c.shape)

(1, 0)
(0,)
(10,)
()
(10, 0)
(10,)
