In [1]:
print "hello world"

SyntaxError: Missing parentheses in call to 'print'. Did you mean print("hello world")? (<ipython-input-1-6d29d8fb337c>, line 1)

In [2]:
print ("hello world")

hello world


In [3]:
import torch
x = torch.empty(3,5)
print(x)

tensor([[1.2096e+04, 7.1846e+22, 1.7718e+28, 4.5144e+27, 0.0000e+00],
        [2.0000e+00, 0.0000e+00, 2.0000e+00, 1.8361e+25, 1.4603e-19],
        [1.6795e+08, 4.7423e+30, 4.7393e+30, 9.5461e-01, 4.4377e+27]])


In [4]:
x = torch.rand(5)
print(x)

tensor([0.8967, 0.9300, 0.1201, 0.3765, 0.0919])


In [5]:
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
这是一个文档


NameError: name '这是一个文档' is not defined

In [7]:
x = torch.tensor([5.5,3])
print(x)


tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5,3,dtype = torch.float64)
print(x)

x = torch.randn_like(x,dtype = torch.float)
print(x)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.5464, -0.4678,  0.6977],
        [-0.1596, -0.3364, -0.3902],
        [ 0.8365,  0.9798,  0.7433],
        [ 0.4608, -1.1703, -1.1357],
        [ 0.5594, -0.3277, -0.0599]])


In [9]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [10]:
y = torch.rand(5,3)
print(y)
print(x + y)

tensor([[0.4598, 0.9628, 0.0198],
        [0.4174, 0.2587, 0.3469],
        [0.5405, 0.8972, 0.0906],
        [0.9198, 0.8448, 0.8198],
        [0.2120, 0.2272, 0.3739]])
tensor([[-0.0866,  0.4949,  0.7175],
        [ 0.2577, -0.0777, -0.0433],
        [ 1.3770,  1.8770,  0.8339],
        [ 1.3806, -0.3255, -0.3159],
        [ 0.7714, -0.1005,  0.3141]])


In [11]:
print(torch.add(x,y))


tensor([[-0.0866,  0.4949,  0.7175],
        [ 0.2577, -0.0777, -0.0433],
        [ 1.3770,  1.8770,  0.8339],
        [ 1.3806, -0.3255, -0.3159],
        [ 0.7714, -0.1005,  0.3141]])


In [12]:
y.add_(x)
print(y)

tensor([[-0.0866,  0.4949,  0.7175],
        [ 0.2577, -0.0777, -0.0433],
        [ 1.3770,  1.8770,  0.8339],
        [ 1.3806, -0.3255, -0.3159],
        [ 0.7714, -0.1005,  0.3141]])


In [13]:
y = x[0, : ]
y += 1
print(y)
print(x[0, : ])

tensor([0.4536, 0.5322, 1.6977])
tensor([0.4536, 0.5322, 1.6977])


In [14]:
print(x)
y = x.view(15)
z = x.view(-1,5)
print(x.shape,y.shape,z.shape)


tensor([[ 0.4536,  0.5322,  1.6977],
        [-0.1596, -0.3364, -0.3902],
        [ 0.8365,  0.9798,  0.7433],
        [ 0.4608, -1.1703, -1.1357],
        [ 0.5594, -0.3277, -0.0599]])
torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [15]:
print(y)
print(z)

tensor([ 0.4536,  0.5322,  1.6977, -0.1596, -0.3364, -0.3902,  0.8365,  0.9798,
         0.7433,  0.4608, -1.1703, -1.1357,  0.5594, -0.3277, -0.0599])
tensor([[ 0.4536,  0.5322,  1.6977, -0.1596, -0.3364],
        [-0.3902,  0.8365,  0.9798,  0.7433,  0.4608],
        [-1.1703, -1.1357,  0.5594, -0.3277, -0.0599]])


In [16]:
x= x+1
print(x)
print(y)

tensor([[ 1.4536,  1.5322,  2.6977],
        [ 0.8404,  0.6636,  0.6098],
        [ 1.8365,  1.9798,  1.7433],
        [ 1.4608, -0.1703, -0.1357],
        [ 1.5594,  0.6723,  0.9401]])
tensor([ 0.4536,  0.5322,  1.6977, -0.1596, -0.3364, -0.3902,  0.8365,  0.9798,
         0.7433,  0.4608, -1.1703, -1.1357,  0.5594, -0.3277, -0.0599])


In [17]:
print(z)

tensor([[ 0.4536,  0.5322,  1.6977, -0.1596, -0.3364],
        [-0.3902,  0.8365,  0.9798,  0.7433,  0.4608],
        [-1.1703, -1.1357,  0.5594, -0.3277, -0.0599]])


In [18]:
y=x.view(15)
x+=1
print(x)
print(y)

tensor([[2.4536, 2.5322, 3.6977],
        [1.8404, 1.6636, 1.6098],
        [2.8365, 2.9798, 2.7433],
        [2.4608, 0.8297, 0.8643],
        [2.5594, 1.6723, 1.9401]])
tensor([2.4536, 2.5322, 3.6977, 1.8404, 1.6636, 1.6098, 2.8365, 2.9798, 2.7433,
        2.4608, 0.8297, 0.8643, 2.5594, 1.6723, 1.9401])


In [19]:
print(z)

tensor([[ 0.4536,  0.5322,  1.6977, -0.1596, -0.3364],
        [-0.3902,  0.8365,  0.9798,  0.7433,  0.4608],
        [-1.1703, -1.1357,  0.5594, -0.3277, -0.0599]])


In [20]:
z=x.view(-1,5)
print(z)

tensor([[2.4536, 2.5322, 3.6977, 1.8404, 1.6636],
        [1.6098, 2.8365, 2.9798, 2.7433, 2.4608],
        [0.8297, 0.8643, 2.5594, 1.6723, 1.9401]])


In [21]:
x = x+1
print(x)
print(z)

tensor([[3.4536, 3.5322, 4.6977],
        [2.8404, 2.6636, 2.6098],
        [3.8365, 3.9798, 3.7433],
        [3.4608, 1.8297, 1.8643],
        [3.5594, 2.6723, 2.9401]])
tensor([[2.4536, 2.5322, 3.6977, 1.8404, 1.6636],
        [1.6098, 2.8365, 2.9798, 2.7433, 2.4608],
        [0.8297, 0.8643, 2.5594, 1.6723, 1.9401]])


In [22]:
x+=1
print(x)
print(z)

tensor([[4.4536, 4.5322, 5.6977],
        [3.8404, 3.6636, 3.6098],
        [4.8365, 4.9798, 4.7433],
        [4.4608, 2.8297, 2.8643],
        [4.5594, 3.6723, 3.9401]])
tensor([[2.4536, 2.5322, 3.6977, 1.8404, 1.6636],
        [1.6098, 2.8365, 2.9798, 2.7433, 2.4608],
        [0.8297, 0.8643, 2.5594, 1.6723, 1.9401]])


In [23]:
z=x.view(-1,5)
print(z)
x+=1
print(z)

tensor([[4.4536, 4.5322, 5.6977, 3.8404, 3.6636],
        [3.6098, 4.8365, 4.9798, 4.7433, 4.4608],
        [2.8297, 2.8643, 4.5594, 3.6723, 3.9401]])
tensor([[5.4536, 5.5322, 6.6977, 4.8404, 4.6636],
        [4.6098, 5.8365, 5.9798, 5.7433, 5.4608],
        [3.8297, 3.8643, 5.5594, 4.6723, 4.9401]])


In [24]:
print(x)

tensor([[5.4536, 5.5322, 6.6977],
        [4.8404, 4.6636, 4.6098],
        [5.8365, 5.9798, 5.7433],
        [5.4608, 3.8297, 3.8643],
        [5.5594, 4.6723, 4.9401]])


In [25]:
print(x)
x_cp = x.clone().view(15)
print(x)
print(x_cp)

tensor([[5.4536, 5.5322, 6.6977],
        [4.8404, 4.6636, 4.6098],
        [5.8365, 5.9798, 5.7433],
        [5.4608, 3.8297, 3.8643],
        [5.5594, 4.6723, 4.9401]])
tensor([[5.4536, 5.5322, 6.6977],
        [4.8404, 4.6636, 4.6098],
        [5.8365, 5.9798, 5.7433],
        [5.4608, 3.8297, 3.8643],
        [5.5594, 4.6723, 4.9401]])
tensor([5.4536, 5.5322, 6.6977, 4.8404, 4.6636, 4.6098, 5.8365, 5.9798, 5.7433,
        5.4608, 3.8297, 3.8643, 5.5594, 4.6723, 4.9401])


In [26]:
print(x)
x_cp = x.clone().view(15)
x=x+1
print(x)
print(x_cp)

tensor([[5.4536, 5.5322, 6.6977],
        [4.8404, 4.6636, 4.6098],
        [5.8365, 5.9798, 5.7433],
        [5.4608, 3.8297, 3.8643],
        [5.5594, 4.6723, 4.9401]])
tensor([[6.4536, 6.5322, 7.6977],
        [5.8404, 5.6636, 5.6098],
        [6.8365, 6.9798, 6.7433],
        [6.4608, 4.8297, 4.8643],
        [6.5594, 5.6723, 5.9401]])
tensor([5.4536, 5.5322, 6.6977, 4.8404, 4.6636, 4.6098, 5.8365, 5.9798, 5.7433,
        5.4608, 3.8297, 3.8643, 5.5594, 4.6723, 4.9401])


In [29]:
#理解一下x=x+1和x+=1在列表操作时的不同！
#分清可变对象和不可变对象，不可变对象的值永远是刚开始创建时候的值，对该对象做的任何操作都会导致一个新的对象的创建。
#可变对象的值可以通过某些操作动态的改变，比如列表对象，可以通过append方法不断地往列表中添加元素，该列表的值就在不断的处于变化中
#一个可变对象赋值给两个变量时他们共享同一个实例对象，指向相同的内存地址，对其中任何一个变量操作时，同时也会影响另外一个变量。
print(x)
y=x.view(15)
x=x+1
print(x)
print(y)

tensor([[8.4536, 8.5322, 9.6977],
        [7.8404, 7.6636, 7.6098],
        [8.8365, 8.9798, 8.7433],
        [8.4608, 6.8297, 6.8643],
        [8.5594, 7.6723, 7.9401]])
tensor([[ 9.4536,  9.5322, 10.6977],
        [ 8.8404,  8.6636,  8.6098],
        [ 9.8365,  9.9798,  9.7433],
        [ 9.4608,  7.8297,  7.8643],
        [ 9.5594,  8.6723,  8.9401]])
tensor([8.4536, 8.5322, 9.6977, 7.8404, 7.6636, 7.6098, 8.8365, 8.9798, 8.7433,
        8.4608, 6.8297, 6.8643, 8.5594, 7.6723, 7.9401])


In [28]:
#+= 操作首先会尝试调用对象的 _iadd_方法，如果没有该方法，那么尝试调用_add_方法。
#add 方法接收两个参数，返回它们的和，两个参数的值均不会改变。 
#iadd 方法同样接收两个参数，但它是属于 in-place 操作，就是说它会改变第一个参数的值，因为这需要对象是可变的，所以对于不可变对象没有iadd方法。
#整数对象是没有iadd的，而列表对象提供了iadd方法
# += 操作调用的是iadd方法, 它会原地修改l指向的那个对象本身的值； + 操作调用的是 add 方法，该方法会返回一个新的对象，原来的对象保持不变。
print(x)
y=x.view(15)
x+=1
print(x)
print(y)

tensor([[7.4536, 7.5322, 8.6977],
        [6.8404, 6.6636, 6.6098],
        [7.8365, 7.9798, 7.7433],
        [7.4608, 5.8297, 5.8643],
        [7.5594, 6.6723, 6.9401]])
tensor([[8.4536, 8.5322, 9.6977],
        [7.8404, 7.6636, 7.6098],
        [8.8365, 8.9798, 8.7433],
        [8.4608, 6.8297, 6.8643],
        [8.5594, 7.6723, 7.9401]])
tensor([8.4536, 8.5322, 9.6977, 7.8404, 7.6636, 7.6098, 8.8365, 8.9798, 8.7433,
        8.4608, 6.8297, 6.8643, 8.5594, 7.6723, 7.9401])


In [30]:
a=1
id(a)
a=a+1
id(a)
a+=1
id(a)

4514890960

In [31]:
a = 1
id(a)

4514890896

In [32]:
a=1
print(id(a))
a=a+1
pringt(id(a))
a+=1
print(id(a))

4514890896


NameError: name 'pringt' is not defined

In [33]:
a=1
print(id(a))
a=a+1
print(id(a))
a+=1
print(id(a))

4514890896
4514890928
4514890960


In [34]:
type(a)

int

In [35]:
x = torch.randn(1)
print(x)
print(x.item())


tensor([-0.4693])
-0.46930015087127686


In [36]:
x = torch.rand(5,3)
print(x)
y = x.trace()
print(y)

tensor([[0.8898, 0.9562, 0.2436],
        [0.2817, 0.0364, 0.7455],
        [0.6534, 0.3813, 0.1047],
        [0.8808, 0.7797, 0.6122],
        [0.2823, 0.6826, 0.6065]])
tensor(1.0310)


In [37]:
print(x.diag())

tensor([0.8898, 0.0364, 0.1047])


In [38]:
print(x.t())

tensor([[0.8898, 0.2817, 0.6534, 0.8808, 0.2823],
        [0.9562, 0.0364, 0.3813, 0.7797, 0.6826],
        [0.2436, 0.7455, 0.1047, 0.6122, 0.6065]])


In [39]:
x = torch.arange(1,3).view(1,2)
print(x)
y = torch.arange(1,4).view(3,1)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [44]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])
id_before = id(y)
print(id_before)
y = y+x
id_then = id(y)
print(id_then)
print(x)

4916030032
4916060880
tensor([1, 2])


In [45]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])
id_before = id(y)
y[ : ] = y + x
id_then = id(y)
print(id_before)
print(id_then)

4916043680
4916043680


In [49]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])
id_before = id(y)
#torch.add(x,y,out = y)   #y += x, y.add_(x)
#y.add_(x)
y+=x
print(id(y)  == id_before)

True


In [50]:
x = tensor.rand(5)
print(x)

NameError: name 'tensor' is not defined

In [53]:
a = torch.ones(5)
b = a.numpy()
print(a)
print(b)
print(a,b)
a+=1
print(a,b)
b+=1
print(a,b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [54]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(a,b)

a+=1
print(a,b)
b+=1
print(a,b)

[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [55]:
c = torch.tensor(a)
a + = 1
print(a,c)

SyntaxError: invalid syntax (<ipython-input-55-21feee0429eb>, line 2)

In [56]:
c = torch.tensor(a)
a+=1
print(a,c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [1]:
x = [1,2,3]
y = [4,5,6]
print(x_y)

NameError: name 'x_y' is not defined

In [2]:
print(x)

[1, 2, 3]


In [3]:
print(map(lambda x_y : x_y[0] + x_y[1],zip(x,y)))

SyntaxError: invalid syntax (<ipython-input-3-eb7030b2aaa4>, line 1)

In [4]:
lambda(x:x+1)

SyntaxError: invalid syntax (<ipython-input-4-14f1b9cf03ff>, line 1)

In [5]:
print(map(lambda x_y : x_y[0] + x_y[1],zip(x,y)))

In [6]:
lambda x_y : x_y[0] + x_y[1] 

<function __main__.<lambda>(x_y)>

In [8]:
f = lambda x_y : x_y[0] + x_y[1] 
a = [1,2]
b = [3,4]
f(a,b)

TypeError: <lambda>() takes 1 positional argument but 2 were given

In [9]:
f = lambda x_y : x_y[0] + x_y[1] 
a = [1,2]
b = [3,4]
f(a_b)

NameError: name 'a_b' is not defined

In [10]:
f(a)

3

In [11]:
a = [1,2,3,4]
f(a)

3

In [12]:
a = [1,2,3,4]
print(f(a))

3


In [10]:
import torch
x = torch.tensor([5.5,3])
print(x)
x = x.new_ones(2,3,dtype = torch.double) #new_* methods take in sizes
print(x)
x= torch.randn_like(x,dtype = torch.float)
print(x)
y = torch.ones_like(x)
print(y)
y = y.new_ones(5,2)
print(y)


tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.0180, -0.3469, -0.4997],
        [-0.2040,  0.6974,  0.0054]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [1]:
import torch
import torch.nn.functional as F
input = torch.randn(3,5)
target = torch.randint(5, (3,), dtype=torch.int64)
loss = F.cross_entropy(input, target)
print(input)
print(target)
print(loss)

tensor([[-0.2853,  0.4404, -0.2662,  1.3695, -0.9997],
        [-1.0363,  1.3654,  0.1773,  2.1698, -0.6005],
        [ 0.7773,  0.5091, -0.5006,  1.3301,  0.3799]])
tensor([0, 4, 4])
tensor(2.4892)
